<?php
/*
Plugin Name: WP Stock Ticker
Plugin URI: https://github.com/younes-wpst/wp-stock-ticker
Description: A WordPress Plugin to display API stock ticker data
Version:1.0.0
Author: Shandy Ward
Author URI: https://shandyward.com/
License: GPL2
License URI: https://www.gnu.org/licenses/gpl-2.0.html
Text Domain:wp-stock-ticker
Domain Path: /languages
*/
defined( 'ABSPATH' ) or die( 'No script kiddies please!' );
// Make sure we don't expose any info if called directly
if ( ! function_exists( 'add_action' ) ){
  exit;
}

/*
* Adds a submenu to the Settings menu.
* the page will contain the ID of html element that hosts our JSX components.
*/
add_action( 'admin_menu', 'wpst_create_menu' );
function wpst_create_menu(){
  add_options_page( 'WP Stock Ticker', 'WP Stock Ticker', 'manage_options', __FILE__,'wpst_display_menu' );
}
function wpst_display_menu(){
  echo '<div id="main"></div>';
}

 function wpst_add_shortcut($atts) {
   $default_atts = array();
  $args = shortcode_atts( $default_atts, $atts );

    return "<div id='tick'></div>";
}

add_shortcode('wp-stock-ticker', 'wpst_add_shortcut');

/**
* we enqueue the Js script generated by WebPack.
*/
add_action( 'wp_enqueue_scripts', 'wpst_enqueue_script' );
function wpst_enqueue_script(){

  wp_enqueue_script(
    'wpst-plugin-reactjs',
    plugins_url('/dist/public/bundle.js', __FILE__) ,
    ['wp-element', 'wp-components'],
    time(), // You can add the current datetime in production env.
    true );
}

function wpst_load_plugin_css() {
    $plugin_url = plugin_dir_url( __FILE__ );

    wp_enqueue_style( 'style1', $plugin_url . 'style.css' );
   
}
add_action( 'wp_enqueue_scripts', 'wpst_load_plugin_css' );




add_action( 'admin_enqueue_scripts', 'wpst_admin_enqueue_script' );
function wpst_admin_enqueue_script(){
  wp_enqueue_script(
    'wpst-plugin-reactjs',
    plugins_url('/dist/public/bundle.js', __FILE__) ,
    ['wp-element', 'wp-components'],
    time(), // You can add the current datetime in production env.
    true );
}



